### ISSUE TITLE
🐞 [Bug]: ending parenthis in URL is truncated with restqa/404-links@2.2.0

### ISSUE THREAD

**Issue by tomdot-dev** [restqa/404-links#35]
### What happened?

When an URL such a link like `[container](https://en.wikipedia.org/wiki/Container_(virtualization))`, 404-links truncates the last parenthesis from it.

### Relevant log output

```shell
> ❌ - [404] - https://en.wikipedia.org/wiki/Container_(virtualization
```

### 🙏 Would you be willing to submit a PR?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by olivierodo** [comment]
On it!
