### ISSUE TITLE
Ignore list with GitHub Actions only ignores last item in list

### ISSUE THREAD

**Issue by gregzealley** [restqa/404-links#6]
When using the `ignore` flag in GitHub actions and passing a list of comma-separated urls, only the last url in the list is ignored.

I have tried the following the following combinations:

ignore: 'https://github.com,https://en.wikipedia.org'
ignore: 'https://github.com, https://en.wikipedia.org'
ignore: "https://github.com,https://en.wikipedia.org"
ignore: "https://github.com, https://en.wikipedia.org"
ignore: https://github.com,https://en.wikipedia.org
ignore: https://github.com, https://en.wikipedia.org

Code section is:

      - name: Check for 404 links      
        if: success() || failure() 
        uses: restqa/404-links@1.0.1
        with:
          path: .
          ignore: https://github.com, https://en.wikipedia.org

Thanks.

**Comment by olivierodo** [comment]
@gregzealley Thank you for feedback let me check

**Comment by olivierodo** [comment]
The latest version is using a yaml file at the root level of the repository. More info on the README
I hope this will enable a better experience.
