### ISSUE TITLE
Link in "About" GitHub section leads to 404

### ISSUE THREAD

**Issue by Marcono1234** [restqa/404-links#8]
The link in the "About" section of this GitHub projects leads to a 404 page:
![About section screenshot](https://user-images.githubusercontent.com/11685886/109829553-edd5e780-7c3d-11eb-815b-14b3ab0eb067.png)

**Comment by olivierodo** [comment]
@Marcono1234, thank you for the notice.
Let me remove it until i fix it.

**Comment by Marcono1234** [comment]
Thanks! I would consider this resolved now, so if you want you can close this issue, but you can also leave it open in case you want to use it for tracking to fix the link.
